---
# Shell role metadata

galaxy_info:
  author: "Devkit Contributors"
  description: "Configure modern shell environments with Zsh, Fish, Oh My Zsh, and Powerlevel10k theme"
  company: "Devkit Project"
  license: "Apache-2.0"
  min_ansible_version: 2.9

  platforms:
    - name: macOS
      versions:
        - 11.0
        - 12.0
        - 13.0
        - 14.0
    - name: Debian
      versions:
        - 10
        - 11
        - 12
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
        - 24.04

  galaxy_tags:
    - shell
    - zsh
    - fish
    - oh-my-zsh
    - powerlevel10k
    - terminal
    - configuration

dependencies:
  - name: core
    scm: git
    src: "https://github.com/vietcgi/devkit.git"
    version: main
