---
# Editors role metadata

galaxy_info:
  author: "Devkit Contributors"
  description: "Configure Neovim, plugins, LSP support, and other editor environments"
  company: "Devkit Project"
  license: "Apache-2.0"
  min_ansible_version: 2.9

  platforms:
    - name: macOS
      versions:
        - 11.0
        - 12.0
        - 13.0
        - 14.0
    - name: Debian
      versions:
        - 10
        - 11
        - 12
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
        - 24.04

  galaxy_tags:
    - editors
    - neovim
    - vim
    - ide
    - lsp
    - development

dependencies:
  - name: core
